#!/usr/bin/env python3
from compile_tool.cli import main
from compile_tool.common import ToolError as RequestError
from compile_tool.common import normalize_hash as normalize_plan_hash
from compile_tool.request import (
    execute_v1 as execute_request,
    load_request,
    normalize_request,
    render_report,
    request_hash,
)


if __name__ == "__main__":
    raise SystemExit(main())
